# This is a values.yaml override file for https://github.com/graphops/helm-charts/tree/main/charts/graph-network-indexer

indexerDefaults:
  config:
    ethereum: "https://eth-goerli.g.alchemy.com/v2/4aQTHR1xzFtOdG9V0Fk8SLTsC2ZXoVfN"
    ethereum-network: "goerli"
    indexer-address: "0x38FDAa37d65BD452EB6c9EDc8413571fED96a896"
    graph-node-query-endpoint: "http://graph-node-query:8000"
    graph-node-status-endpoint: "http://graph-node-index:8030/graphql"
    postgres-host: "pg-indexer-metadata"
    postgres-database: "indexer"
    network-subgraph-endpoint: "https://gateway.testnet.thegraph.com/network"

  env: {}
  secretEnv: {}

indexerAgent:
  config:
    graph-node-admin-endpoint: "http://graph-node-index:8020"
    public-indexer-url: "XXX_CHANGEME_XXX" #do we need a domain?
    index-node-ids: "graph-node-index-0" # TODO this should be removed as a requirement, in the mean time it should be a comma delimited list of index node ids
    collect-receipts-endpoint: "https://gateway.testnet.thegraph.com/collect-receipts"
    network-subgraph-deployment: "QmeTrzKtD7fuNScLZFE4QtcmFqNfcePRumkHNdZhoZSA3G" # find at https://github.com/graphprotocol/indexer/blob/main/docs/networks.md
    dai-contract: "0x9e7e607afd22906f7da6f1ec8f432d6f244278be" # find at https://github.com/graphprotocol/indexer/blob/main/docs/networks.md
    epoch-subgraph-endpoint: "https://api.thegraph.com/subgraphs/name/graphprotocol/goerli-epoch-block-oracle" # find at https://github.com/graphprotocol/indexer/blob/main/docs/networks.md

  env: {}

  secretEnv:
    INDEXER_AGENT_MNEMONIC:
      secretName: graph-operator-mnemonic
      key: mnemonic
    INDEXER_AGENT_POSTGRES_USERNAME:
      secretName: indexer.pg-indexer-metadata.credentials.postgresql.acid.zalan.do
      key: username
    INDEXER_AGENT_POSTGRES_PASSWORD:
      secretName: indexer.pg-indexer-metadata.credentials.postgresql.acid.zalan.do
      key: password


indexerService:
  replicaCount: 1 # scale me
  config:
    client-signer-address: "0xe1EC4339019eC9628438F8755f847e3023e4ff9c" # find at https://github.com/graphprotocol/indexer/blob/main/docs/networks.md

  env: {}

  secretEnv:
    INDEXER_SERVICE_MNEMONIC:
      secretName: graph-operator-mnemonic
      key: mnemonic
    INDEXER_SERVICE_POSTGRES_USERNAME:
      secretName: indexer.pg-indexer-metadata.credentials.postgresql.acid.zalan.do
      key: username
    INDEXER_SERVICE_POSTGRES_PASSWORD:
      secretName: indexer.pg-indexer-metadata.credentials.postgresql.acid.zalan.do
      key: password

prometheus:
  serviceMonitors:
    enabled: true

grafana:
  dashboards: true
